/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle;

import java.awt.Color;
import java.awt.Dimension;

import java.awt.Toolkit;

import javax.swing.JFrame;

import javax.swing.JButton;

import java.awt.event.ActionEvent;

import java.awt.event.ActionListener;

public class App extends JFrame {
    
    boolean colorChanged = false;

    public String getGreeting() {
        return "Hello World!";
    }

    public void botonPresionado(){
        System.out.println("Me presionaste");
    }

    public void otraPantalla(JFrame original){
        App frame = new App();
        original.dispose();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 1000);
        frame.setTitle("Secondary Frame");
        frame.setLocation(1000,500);
    }

    public static void main(String[] args) {
        /*Constantes*/
        int frameWidth = 1000;
        int frameHeight = 400;
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        /*Frame */
        //JFrame frame = new JFrame();
        App frame = new App();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        frame.setSize(frameWidth, frameHeight);
        frame.setTitle("Frame de David");
        //frame.setLocation(400,100);
        frame.setLocation((screenWidth - frameWidth)/2,(screenHeight - frameHeight)/2);
        
        /*Elementos del Frame*/
        JButton button = new JButton("Este es el texto que se pone");
        button.setBounds(frameWidth/2, frameHeight/2, 400, 40);
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Lo que sea, fui presionado");
                if(!frame.colorChanged){
                    frame.getContentPane().setBackground(Color.RED);
                    frame.colorChanged = true;
                }
                else{
                    frame.getContentPane().setBackground(Color.GRAY);
                    frame.colorChanged = false;
                }
                //frame.botonPresionado();
                // frame.removeAll();
                // frame.dispose();
            }
        });

        frame.add(button);

        /*Hacer Frame Visible */
        frame.setLayout(null);
        frame.setVisible(true);
    }
}
