/*
 * This source file was generated by the Gradle 'init' task
 */
package gradle;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;

public class App extends JFrame {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JFrame frame = new App();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 200);
        frame.setTitle("Gradle Java Application");
        frame.setVisible(true);
    }
}
