    /*
    * This source file was generated by the Gradle 'init' task
    */
    package ejercicio_examen;

    import java.awt.Color;

    import javax.swing.JButton;
    import javax.swing.JComboBox;
    import javax.swing.JFrame;
    import javax.swing.JLabel;
    import javax.swing.JTable;
    import javax.swing.JTextField;

    import java.awt.Dimension;
    import java.awt.Toolkit;
    import java.awt.event.ActionEvent;
    import java.awt.event.ActionListener;

    public class App extends JFrame{
        int frameWidth = 1000;
        int frameHeight = 600;

        public void colocarTabla(){
            System.out.println("Colocar una tabla");
        }

        public void nuevaVentana(App originalFrame){
            App frame = new App();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;
            
            /* Frame */

            frame.setLayout(null);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            //frame.getContentPane().setBackground(Color.YELLOW);
            frame.setSize(frame.frameWidth,frame.frameHeight);
            frame.setTitle("Ingrese Datos Alumno");
            frame.setLocation((screenWidth - frame.frameWidth)/2,(screenHeight - frame.frameHeight)/2);

            /*Labels del Frame */

            JLabel nombreAlumno = new JLabel("Nombre del Alumno:");
            nombreAlumno.setBounds(0, 0, 400, 40);
            frame.add(nombreAlumno);

            JLabel apellidoAlumno = new JLabel("Apellido del Alumno:");
            apellidoAlumno.setBounds(0, 40, 400, 40);
            frame.add(apellidoAlumno);

            JLabel boletaAlumno = new JLabel("Boleta del Alumno:");
            boletaAlumno.setBounds(0, 80, 400, 40);
            frame.add(boletaAlumno);

            JLabel grupoAnteriorAlumno = new JLabel("Grupo Anterior del Alumno:");
            grupoAnteriorAlumno.setBounds(0, 120, 400, 40);
            frame.add(grupoAnteriorAlumno);

            JLabel calificacionesAlumno = new JLabel("Primera Calificación del Alumno:");
            calificacionesAlumno.setBounds(0, 160, 400, 40);
            frame.add(calificacionesAlumno);

            /*Inputs del Frame */

            JTextField datoNombreAlumno = new JTextField();
            datoNombreAlumno.setBounds(400, 0, 600, 40);
            frame.add(datoNombreAlumno);

            JTextField datoApellidoAlumno = new JTextField("");
            datoApellidoAlumno.setBounds(400, 40, 600, 40);
            frame.add(datoApellidoAlumno);

            JTextField datoBoletaAlumno = new JTextField("");
            datoBoletaAlumno.setBounds(400, 80, 600, 40);
            frame.add(datoBoletaAlumno);

            JTextField datoGrupoAlumno = new JTextField("");
            datoGrupoAlumno.setBounds(400, 120, 600, 40);
            frame.add(datoGrupoAlumno);

            /* JComboBox */

            JComboBox datosCalificaciones1Box = new JComboBox<>();
            datosCalificaciones1Box.addItem("0");
            datosCalificaciones1Box.addItem("1");
            datosCalificaciones1Box.addItem("2");
            datosCalificaciones1Box.addItem("3");
            datosCalificaciones1Box.addItem("4");
            datosCalificaciones1Box.addItem("5");
            datosCalificaciones1Box.addItem("6");
            datosCalificaciones1Box.addItem("7");
            datosCalificaciones1Box.addItem("8");
            datosCalificaciones1Box.addItem("9");
            datosCalificaciones1Box.addItem("10");
            datosCalificaciones1Box.setBounds(400, 160, 600, 40);
            frame.add(datosCalificaciones1Box);

            /* Botones */



            frame.setVisible(true);
        }

        public static void main(String[] args) {
            App frame = new App();
            
            /*Obtener el tamaño de la pantalla*/
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;

            /*Propiedades del JFrame */
            frame.setLayout(null);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            //frame.getContentPane().setBackground(Color.YELLOW);
            frame.setSize(frame.frameWidth,frame.frameHeight);
            frame.setTitle("Examen David 2025");
            frame.setLocation((screenWidth - frame.frameWidth)/2,(screenHeight - frame.frameHeight)/2);

            /*Tabla del JFrame */
            

            /* Botón para añadir alumnos */
            JButton botonAnadirAlumno = new JButton("Añadir Nuevo Alumno");
            botonAnadirAlumno.setSize(300, 40);
            botonAnadirAlumno.setLocation((frame.frameWidth-300)/2,0);
            botonAnadirAlumno.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    frame.setVisible(false);
                    frame.nuevaVentana(frame);
                }
            });
            
            frame.add(botonAnadirAlumno);

            /*Hacer Frame Visible */
            frame.setVisible(true);
            frame.colocarTabla();
        }
    }
